snapshot

diff --git a/dotfiles/bash_functions b/dotfiles/bash_functions
--- a/dotfiles/bash_functions
+++ b/dotfiles/bash_functions
@@ -1,62 +1,72 @@
 # .bash_functions
 # vim: ft=sh
 
-realwhich() {
-    realpath "$(command which "$@")"
+realwhich()
+{
+    realpath $(command which "$@")
 }
 
-doihave() {
-    command which "$@" &>/dev/null
+doihave()
+{
+    command which "$@" &> /dev/null
 }
 # so i can type `if ihave program; ...`
 alias ihave=doihave
 
-heregit() {
-    # execute a git command in every child directory
-    local item
-    for item in *; do
-        echo -e "\e[30;43m> $item\e[0m"
-        git -C "$item" "$@"
-        echo
-    done
-}
-
-# files() {
-# 	# like `find -type f`, but exclude hidden files
-# 	find "$@" -iregex ".*/\.[^/].*" -prune -o -type f -print
+# this is a script now
+# heregit()
+# {
+#     : 'execute a git command in every child directory'
+#     local item
+#     for item in *; do
+#         echo -e "\e[30;43m> $item\e[0m"
+#         git -C "$item" "$@"
+#         echo
+#     done
 # }
 
-files() {
-    # list regular files, here or at given paths
+# files() {
+#   : like `find -type f`, but exclude hidden files
+#   find "$@" -iregex ".*/\.[^/].*" -prune -o -type f -print
+# }
+
+files()
+{
+    : 'list regular files, here or at given paths'
     fd . -t f "$@"
 }
 
-vimfiles() {
+vimfiles()
+{
     vim -p $(files "$@")
 }
 # if we have `_filedir` from bash completion, use it
-declare -F _filedir &>/dev/null && complete -F _filedir -d vimfiles
+declare -F _filedir &> /dev/null && complete -F _filedir -d vimfiles
 
-vimwhich() {
+vimwhich()
+{
     vim $(realwhich "$@")
 }
 complete -c vimwhich
 
-nvfiles() {
+nvfiles()
+{
     nv $(files "$@")
 }
 # if we have `_filedir` from bash completion, use it
-declare -F _filedir &>/dev/null && complete -F _filedir -d nvfiles
+declare -F _filedir &> /dev/null && complete -F _filedir -d nvfiles
 
-nvwhich() {
+nvwhich()
+{
     nv $(realwhich "$@")
 }
 complete -c nvwhich
 
-# mnemonic "move with"
-# move a file & cd to that directory
-mw() {
-    if [[ $# -lt 2 || " $@ " =~ " -h " || " $@ " =~ " --help " ]]; then
+mw()
+{
+    : 'move a file & cd to that directory'
+    # mnemonic "move with"
+    if [[ $# -lt 2 || " $* " =~ " -h " || " $* " =~ " --help " ]]; then
         echo "mw: FILE... DIR -> mv FILE... DIR && cd DIR"
         exit 1
     fi
@@ -68,61 +78,64 @@ mw() {
         echo "last parameter should be a directory"
         return 1
     }
-    mv -t "$dest" "${files[@]}" && cd "$dest"
+    mv -t "$dest" "${files[@]}" && cd "$dest" || return
 }
 # if we have `_filedir` from bash completion, use it
-declare -F _filedir &>/dev/null && complete -F _filedir mw
+declare -F _filedir &> /dev/null && complete -F _filedir mw
 
-repeat() {
-    # usage: repeat TEXT COUNT
-    # does something a bit like `TEXT * COUNT`
+repeat()
+{
+    : 'usage: repeat TEXT COUNT'
+    : 'does something a bit like `TEXT * COUNT`'
     local text="$1"
     local count="$2"
-    printf "${text}%.0s" $(seq 1 $count)
+    printf "${text}%.0s" $(seq 1 "$count")
 }
 
-pathmunge() {
-    # add a directory to the PATH if not already present
+pathmunge()
+{
+    : 'add a directory to the PATH if not already present'
     case ":${PATH}:" in
-    *:"$1":*) ;;
-    *)
-        if [ -d "$1" ]; then
-            if [ "$2" = "after" ]; then
-                PATH=$PATH:$1
-            else
-                PATH=$1:$PATH
+        *:"$1":*) ;;
+        *)
+            if [ -d "$1" ]; then
+                if [ "$2" = "after" ]; then
+                    PATH=$PATH:$1
+                else
+                    PATH=$1:$PATH
+                fi
             fi
-        fi
-        ;;
+            ;;
     esac
 }
 
-pathmungex() {
-    # like pathmunge, but better
+pathmungex()
+{
+    : 'like pathmunge, but better'
     local params arg PATHVAR DIR EXPORT AFTER HELP
     params=(PATHVAR DIR)
     while [[ $# -gt 0 ]]; do
         arg="$1"
         shift
         case $arg in
-        -e | --export) EXPORT=1 ;;
-        -a | --after) AFTER=1 ;;
-        -h | --help) HELP=1 ;;
-        -*)
-            echo >&2 "[X] I don't understand \"$arg\""
-            HELP=1
-            ;;
-        *)
-            : "setting a positional parameter: ${params[0]} -> $arg"
-            if [[ ${#params[@]} -gt 0 ]]; then
-                param="${params[0]}"
-                declare "$param=$arg"
-                params=("${params[@]:1}")
-            else
-                echo >&2 "[X] Too many parameters: \"$arg\""
+            -e | --export) EXPORT=1 ;;
+            -a | --after) AFTER=1 ;;
+            -h | --help) HELP=1 ;;
+            -*)
+                echo >&2 "[X] I don't understand \"$arg\""
                 HELP=1
-            fi
-            ;;
+                ;;
+            *)
+                : "setting a positional parameter: ${params[0]} -> $arg"
+                if [[ ${#params[@]} -gt 0 ]]; then
+                    param="${params[0]}"
+                    declare "$param=$arg"
+                    params=("${params[@]:1}")
+                else
+                    echo >&2 "[X] Too many parameters: \"$arg\""
+                    HELP=1
+                fi
+                ;;
         esac
     done
 
@@ -160,41 +173,44 @@ pathmungex() {
     fi
 }
 
-showmounts() {
-    # list mounts in a table, and cut off the options
+showmounts()
+{
+    : 'list mounts in a table, and cut off the options'
     mount -l "$@" | cut -d "(" -f 1 | sed -r "s/\<(on|type)\>/% \0/g" | column -t -s %
 }
 
-flash_message() {
+flash_message()
+{
+    : 'breifly print a message to the screen'
     local arg message HELP
     local sleep=1
     while [[ $# -gt 0 ]]; do
         arg="$1"
         shift
         case $arg in
-        -s | --sleep)
-            sleep="$1"
-            shift
-            ;;
-        -h | --help)
-            HELP=1
-            ;;
-        -*)
-            echo >&2 "Unrecognized option: $arg"
-            ;;
-        *)
-            message+="$arg "
-            ;;
+            -s | --sleep)
+                sleep="$1"
+                shift
+                ;;
+            -h | --help)
+                HELP=1
+                ;;
+            -*)
+                echo >&2 "Unrecognized option: $arg"
+                ;;
+            *)
+                message+="$arg "
+                ;;
         esac
     done
 
     if [[ -v HELP ]]; then
-        command cat <<EOF
+        command cat << EOF
 flash_message: briefly print a message to the screen.
 
 Usage: flash_message [-s|--sleep SLEEP] MESSAGE...
 
-	-s|--sleep: how long to sleep (currently $sleep)
+    -s|--sleep: how long to sleep (currently $sleep)
 EOF
         return 1
     fi
@@ -206,26 +222,31 @@ EOF
     tput ed
 }
 
-function vim() {
-    flash_message -s 2 '!!! use nv !!!'
-    nvim "$@"
-    return $?
-}
+# vim()
+# {
+#     flash_message -s 2 '!!! use nv !!!'
+#     nvim "$@"
+#     return $?
+# }
 
 # don't wanna set pager globally, but do wanna pick one for these
 doihave bat && _pager=bat || _pager=less
 
-# mnemonic: `jq | less`
-function jql() {
+jql()
+{
+    : 'mnemonic: `jq | less`'
     jq -C "${@:-.}" | $_pager
 }
 
-# mnemonic: `jq | less`
-function yql() {
+yql()
+{
+    : 'mnemonic: `yq | less`'
     yq -C "${@:-.}" | $_pager
 }
 
-pkg-config-vars() {
+pkg-config-vars()
+{
+    : 'display all pkg-config variables for a name'
     for name in "$@"; do
         pkg-config "$name" --print-variables | while read -r var; do
             value=$(pkg-config "$name" --variable "$var")
@@ -234,13 +255,172 @@ pkg-config-vars() {
     done
 }
 
-pkg-config-names() {
-    pkg-config --list-all | cut -f1 -d" "
+pkg-config-names()
+{
+    pkg-config --list-all | cut -f1 -d" " | sort
 }
 
-_complete-pkg-config-names() {
-    COMPREPLY=($(compgen -W "$(pkg-config-names)" -- "${COMP_WORDS[COMP_CWORD]}"))
+_complete-pkg-config-names()
+{
+    # COMPREPLY=($(compgen -W "$(pkg-config-names)" -- "${COMP_WORDS[COMP_CWORD]}"))
+    read -ra COMPREPLY <<< "$(compgen -W "$(pkg-config-names)" -- "${COMP_WORDS[COMP_CWORD]}")"
     return 0
 }
 
 complete -F _complete-pkg-config-names pkg-config-vars
+
+dush()
+{
+    command du -shc "$@" | sort -h
+}
+
+each()
+{
+    for item in "$@"; do
+        echo "$item"
+    done
+}
+
+showpaths()
+{
+    : 'pretty print pathlike variables'
+    : 'usage: showpaths [PATHVAR...]'
+    status=0
+
+    # make a list of parameters, defaulting to just "PATH"
+    paths=("${@:-PATH}")
+
+    for item in "${paths[@]}"; do
+        if [[ ! -v $item ]]; then
+            # if there's no variable with that name, warn & continue
+            echo >&2 "[X] $item unset"
+            status=1
+            continue
+        fi
+
+        # if more than one argument, print a header
+        [[ ${#paths[@]} -gt 1 ]] && echo "===== $item ====="
+        # echo path variable contents, one per line
+        echo "${!item}" | tr : "\n"
+    done
+    return $status
+}
+complete -v showpaths
+
+searchpath()
+{
+    : 'search a pathlike variable'
+    : 'usage: searchpath PATHVAR name [name...]'
+
+    [[ $# -lt 2 ]] && return 1
+
+    pathvar="$1"
+    shift
+    names=("$@")
+
+    if [[ ! -v $pathvar ]]; then
+        # if there's no variable with that name, explode
+        echo >&2 "[X] $pathvar unset"
+        return 1
+    fi
+
+    # read contents of variable named by `pathvar` into array, separated by colons
+    mapfile -td: pathlist <<< "${!pathvar}"
+
+    for path in "${pathlist[@]}"; do
+        for name in "${names[@]}"; do
+            # expand any globs & print existing files
+            compgen -G "$path/$name"
+        done
+    done
+
+}
+complete -v searchpath
+
+fatal()
+{
+    : 'display an error with an optional message; stacktrace; exit 1'
+    echo >&2 "[X] ${*:-Fatal Error}"
+    stacktrace
+    exit 1
+}
+
+stacktrace()
+{
+    : 'print the current call stack'
+    local idx filename subroutine lineno context lines ctx_lineno prefix
+
+    context=2
+    top=1
+    bottom=1
+
+    local opt OPTARG OPTIND help
+    while getopts :hc:t:b: opt; do
+        case $opt in
+            h)
+                help=1
+                ;;
+            c)
+                context=$OPTARG
+                ;;
+            t)
+                top=$OPTARG
+                ;;
+            b)
+                bottom=$OPTARG
+                ;;
+            :)
+                echo >&2 "[X] required argument not found: $OPTARG"
+                help=1
+                ;;
+            ?)
+                echo >&2 "[X] invalid option: $OPTARG"
+                help=1
+                ;;
+            *)
+                echo >&2 "[X] unexpected input"
+                declare -p opt OPTARG
+                help=1
+                ;;
+        esac
+    done
+    shift $((OPTIND - 1))
+
+    if [[ -v help ]]; then
+        cat >&2 << EOF
+$FUNCNAME: print a bash function stacktrace
+Usage: $FUNCNAME [-h] [-c CONTEXT] [-b BOTTOM] [-t TOP]
+
+Options:
+-c CONTEXT      print CONTEXT number of lines of context (currently $context)
+-b BOTTOM       trim BOTTOM frames from the bottom of the stack (currently $bottom)
+-t TOP          trim TOP frames from the top of the stack (currently $top)
+EOF
+        return 1
+    fi
+
+    echo "  Call stack (starting with oldest frame):"
+    # iterating through 3 related arrays in reverse; -1 for array end ; idx > 0 to skip this function
+    for ((idx = ${#BASH_SOURCE[@]} - bottom; idx >= top; idx--)); do
+        filename=${BASH_SOURCE[$idx]}
+        subroutine=${FUNCNAME[$idx]}
+        lineno=${BASH_LINENO[$idx - 1]}
+
+        unset lines
+        # read into array $lines from $filename at $lineno
+        # (such that $index = $lineno) with $context surrounding lines
+        mapfile -s $((lineno - context - 1)) -O $((lineno - context)) -n $((context * 2 + 1)) -t lines < "$filename"
+
+        echo "    $filename($subroutine):"
+        for ctx_lineno in "${!lines[@]}"; do
+            ((ctx_lineno == lineno)) && prefix="   >>" || prefix="     "
+            echo "$prefix $ctx_lineno ${lines[$ctx_lineno]}"
+        done
+
+    done
+}
+
+faketty()
+{
+    script -qefc "$(printf "%q " "$@")" /dev/null
+}
diff --git a/dotfiles/bashrc b/dotfiles/bashrc
--- a/dotfiles/bashrc
+++ b/dotfiles/bashrc
@@ -48,6 +48,8 @@ LOCAL_BASH_COMPLETION=/usr/local/share/bash-completion/bash_completion
 [[ -f $HOME/.bash_functions ]] && . "$HOME/.bash_functions"
 
 # counter-intuitively, later lines will be higher in the path
+pathmungex PATH "/usr/local/go/bin"
+
 pathmungex PATH "$HOME/workspace/maxar/dodev"
 
 pathmungex PATH "$HOME/.local/share/plantuml"
@@ -80,9 +82,9 @@ pathmungex PATH "$HOME/.maxar-bin"
 
 pathmungex --after PATH /usr/pgsql-12/bin
 
-export PERL_MB_OPT="--install_base /home/tbozeman/perl5"
-export PERL_MM_OPT="INSTALL_BASE=/home/tbozeman/perl5"
-pathmungex PATH /home/tbozeman/perl5/bin
+export PERL_MB_OPT="--install_base $HOME/perl5"
+export PERL_MM_OPT="INSTALL_BASE=$HOME/perl5"
+pathmungex PATH "$HOME/perl5/bin"
 pathmungex -e -a PERL_LOCAL_LIB_ROOT "$HOME/perl5"
 pathmungex -e PERL5LIB "$HOME/perl5/lib/perl5"
 
@@ -111,10 +113,14 @@ HISTCONTROL=ignoreboth
 shopt -s histappend
 
 # for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
-HISTSIZE=
-HISTFILESIZE=
-HISTTIMEFORMAT="%h %d %H:%M:%S> "
+# bash 4.2 doesn't seem to like negative values here...
+# HISTSIZE="-1"
+# HISTFILESIZE="-1"
+HISTSIZE=$((2 ** 20))
+HISTFILESIZE=$HISTSIZE
 HISTIGNORE="ls:la:lf:ll:l"
+# HISTTIMEFORMAT="%h %d %H:%M:%S> "
+HISTTIMEFORMAT="%Y-%m-%d %H:%M:%S> "
 
 # check the window size after each command and, if necessary,
 # update the values of LINES and COLUMNS.
@@ -127,6 +133,10 @@ export RSYNC_RSH="ssh -i $HOME/.ssh/rsync_key"
 shopt -s autocd
 # set recursive globbing w/ "**"
 shopt -s globstar
+# I wanna set this, but it seems like it would probably break things...
+# shopt -s nocaseglob
+# if any command in a pipeline fails, the pipeline should be considered to have failed
+shopt -so pipefail
 
 # attempt to set some options for LESS LESS="-SRFXJ"
 export LESS="-SRFi"
@@ -154,10 +164,8 @@ export NVM_DIR="$HOME/.nvm"
 
 # [ -z $SSH_AUTH_SOCK ] && eval $(ssh-agent -s) >/dev/null 2>&1
 
-export PYENV_ROOT=$HOME/.pyenv
-
-# export M2_HOME=/home/tbozeman/.bootstrap/maven/default
-# export JAVA_HOME=$HOME/.bootstrap/java/default
+# export M2_HOME="$HOME/.bootstrap/maven/default"
+# export JAVA_HOME="$HOME/.bootstrap/java/default"
 
 export SSL_CERT_FILE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
 
@@ -189,33 +197,20 @@ export DOCKER_COMPLETION_SHOW_PLUGIN_IDS=yes
 export DOCKER_COMPLETION_SHOW_SECRET_IDS=yes
 export DOCKER_COMPLETION_SHOW_SERVICE_IDS=yes
 
-pathmungex -e PKG_CONFIG_PATH "$HOME/local/lib/pkgconfig"
-pathmungex -e PKG_CONFIG_PATH "$HOME/local/lib64/pkgconfig"
-pathmungex -e PKG_CONFIG_PATH "$HOME/local/share/pkgconfig"
-pathmungex -e PKG_CONFIG_PATH /usr/local/lib/pkgconfig
-pathmungex -e PKG_CONFIG_PATH /usr/local/lib64/pkgconfig
-pathmungex -e PKG_CONFIG_PATH /usr/local/share/pkgconfig
+export PKG_CONFIG_PATH
+pathmungex PKG_CONFIG_PATH /usr/share/pkgconfig
+pathmungex PKG_CONFIG_PATH /usr/lib64/pkgconfig
+pathmungex PKG_CONFIG_PATH /usr/lib/pkgconfig
+pathmungex PKG_CONFIG_PATH /usr/local/share/pkgconfig
+pathmungex PKG_CONFIG_PATH /usr/local/lib64/pkgconfig
+pathmungex PKG_CONFIG_PATH /usr/local/lib/pkgconfig
+pathmungex PKG_CONFIG_PATH "$HOME/local/share/pkgconfig"
+pathmungex PKG_CONFIG_PATH "$HOME/local/lib64/pkgconfig"
+pathmungex PKG_CONFIG_PATH "$HOME/local/lib/pkgconfig"
 
 for item in ~/.profile.d/*.{sh,bash}; do
-    [[ -f $item && -r $item ]] && . $item
+    [[ -f $item && -r $item ]] && . "$item"
 done
 unset item
-
-# -------- SNIP --------
-
-# # >>> conda initialize >>>
-# # !! Contents within this block are managed by 'conda init' !!
-# __conda_setup=$($HOME/.bootstrap/miniconda/bin/conda shell.bash hook 2> /dev/null)
-# if [ $? -eq 0 ]; then
-#     eval "$__conda_setup"
-# else
-#     if [ -f "$HOME/.bootstrap/miniconda/etc/profile.d/conda.sh" ]; then
-#         . "$HOME/.bootstrap/miniconda/etc/profile.d/conda.sh"
-#     else
-#         export PATH="$HOME/.bootstrap/miniconda/bin:$PATH"
-#     fi
-# fi
-# unset __conda_setup
-# # <<< conda initialize <<<
 
 : end of bashrc
