checkpoint

diff --git a/dotfiles/bash_functions b/dotfiles/bash_functions
--- a/dotfiles/bash_functions
+++ b/dotfiles/bash_functions
@@ -1,133 +1,226 @@
 # .bash_functions
-# vim: ft=sh
+# shellcheck disable=SC2016
+# vim: ft=sh ts=4 sw=4 et
 
-realwhich() {
-    realpath "$(command which "$@")"
+realwhich()
+{
+    : '`which` without aliases or functions, dereferencing symlinks'
+    # {
+    #     command which "$@" || return
+    # } | xargs -r realpath
+    declare -a items
+    local item failures
+    for item in "$@"; do
+        # i just don't like the error output of `which`...
+        items+=("$(command which "$item" 2> /dev/null)") || {
+            echo >&2 "[X] realwhich: did not find $item"
+            failures=1
+        }
+    done
+    [[ -v failures ]] && return 1
+    realpath "${items[@]}"
 }
 
-doihave() {
-    command which "$@" &>/dev/null
+doihave()
+{
+    : 'silently test whether a command is in the path'
+    command which "$@" &> /dev/null
 }
 # so i can type `if ihave program; ...`
 alias ihave=doihave
 
-heregit() {
-    # execute a git command in every child directory
-    local item
-    for item in *; do
-        echo -e "\e[30;43m> $item\e[0m"
-        git -C "$item" "$@"
-        echo
-    done
-}
-
-# files() {
-# 	# like `find -type f`, but exclude hidden files
-# 	find "$@" -iregex ".*/\.[^/].*" -prune -o -type f -print
+# this is a script now
+# heregit()
+# {
+#     : 'execute a git command in every child directory'
+#     local item
+#     for item in *; do
+#         echo -e "\e[30;43m> $item\e[0m"
+#         git -C "$item" "$@"
+#         echo
+#     done
 # }
 
-files() {
-    # list regular files, here or at given paths
-    fd . -t f "$@"
+# this is an alias now (using `fd`)
+# files() {
+#   : 'like "find -type f", but exclude hidden files'
+#   find "$@" -iregex ".*/\.[^/].*" -prune -o -type f -print
+# }
+
+get_array()
+{
+    : '`readarray` with error handling'
+    : 'usage: get_array [READARRAY_ARGS...] ARRAY -- COMMAND...'
+    declare -a mapargs
+    while [[ $# -gt 0 ]]; do
+        local arg=$1
+        shift
+        case $arg in
+            --) break ;;
+            *) mapargs+=("$arg") ;;
+        esac
+    done
+    if [[ $# -eq 0 ]]; then
+        echo >&2 "[X] get_array: no command given"
+        return 1
+    elif [[ ${#mapargs[*]} -eq 0 ]]; then
+        # technically you could call like `get_array -d : -- echo $PATH` and
+        # pass this check, but if you've gotten that far, i'll assume you know
+        # what you're doing
+        echo >&2 "[X] get_array: no array given"
+        return 1
+    fi
+
+    # execute the command
+    local fulltext
+    fulltext=$("$@") || {
+        local err=$?
+        echo >&2 -n "$fulltext"
+        return $err
+    }
+
+    # map the array
+    readarray -t "${mapargs[@]}" <<< "$fulltext"
 }
 
-vimfiles() {
-    vim -p $(files "$@")
+with_files()
+{
+    : 'run a command & pass `files` as parameters'
+    : 'usage: with_files COMMAND [COMMAND_ARGS...] [-- FILES_ARGS...]'
+    # split our params into command and files_args
+    declare -a command files
+    while [[ $# -gt 0 ]]; do
+        local arg="$1"
+        shift
+        case $arg in
+            --) break ;;
+            *) command+=("$arg") ;;
+        esac
+    done
+    #
+    # remaining args, if any, go to `fd`
+    get_array files -- fd -t f . "$@" || return
+    # check for empty set
+    [[ ${#files[*]} -eq 0 ]] && {
+        echo >&2 "[X] no files"
+        return 1
+    }
+    # handoff
+    "${command[@]}" "${files[@]}"
+}
+
+vimfiles()
+{
+    : 'edit all regular files (in $@ or .) with vim'
+    with_files vim -- "$@"
 }
 # if we have `_filedir` from bash completion, use it
-declare -F _filedir &>/dev/null && complete -F _filedir -d vimfiles
+declare -F _filedir &> /dev/null && complete -F _filedir -d vimfiles
 
-vimwhich() {
-    vim $(realwhich "$@")
+vimwhich()
+{
+    declare -a targets
+    get_array targets -- realwhich "$@" || return
+    vim "${targets[@]}"
 }
 complete -c vimwhich
 
-nvfiles() {
-    nv $(files "$@")
+nvfiles()
+{
+    with_files nvim -- "$@"
 }
 # if we have `_filedir` from bash completion, use it
-declare -F _filedir &>/dev/null && complete -F _filedir -d nvfiles
+declare -F _filedir &> /dev/null && complete -F _filedir -d nvfiles
 
-nvwhich() {
-    nv $(realwhich "$@")
+nvwhich()
+{
+    declare -a targets
+    # mapfile -t targets < <(realwhich "$@") || return
+    # targets=($(realwhich "$@"))
+    get_array targets -- realwhich "$@" || return
+    nvim "${targets[@]}"
 }
 complete -c nvwhich
 
-# mnemonic "move with"
-# move a file & cd to that directory
-mw() {
-    if [[ $# -lt 2 || " $@ " =~ " -h " || " $@ " =~ " --help " ]]; then
+mw()
+{
+    : 'move a file & cd to that directory'
+    # mnemonic "move with"
+    if [[ $# -lt 2 || " $* " =~ " -h " || " $* " =~ " --help " ]]; then
         echo "mw: FILE... DIR -> mv FILE... DIR && cd DIR"
         exit 1
     fi
     # the last parameter
-    local dest="${@: -1}"
+    local dest="${*: -1}"
     # everything but the last parameter, as an array
     local files=("${@:1:$#-1}")
     [[ -d $dest ]] || {
         echo "last parameter should be a directory"
         return 1
     }
-    mv -t "$dest" "${files[@]}" && cd "$dest"
+    mv -t "$dest" "${files[@]}" && cd "$dest" || return
 }
 # if we have `_filedir` from bash completion, use it
-declare -F _filedir &>/dev/null && complete -F _filedir mw
+declare -F _filedir &> /dev/null && complete -F _filedir mw
 
-repeat() {
-    # usage: repeat TEXT COUNT
-    # does something a bit like `TEXT * COUNT`
+repeat()
+{
+    : 'usage: repeat TEXT COUNT'
+    : 'does something a bit like `TEXT * COUNT`'
     local text="$1"
     local count="$2"
-    printf "${text}%.0s" $(seq 1 $count)
+    printf "${text}%.0s" $(seq 1 "$count")
 }
 
-pathmunge() {
-    # add a directory to the PATH if not already present
+pathmunge()
+{
+    : 'add a directory to the PATH if not already present'
     case ":${PATH}:" in
-    *:"$1":*) ;;
-    *)
-        if [ -d "$1" ]; then
-            if [ "$2" = "after" ]; then
-                PATH=$PATH:$1
-            else
-                PATH=$1:$PATH
+        *:"$1":*) ;;
+        *)
+            if [ -d "$1" ]; then
+                if [ "$2" = "after" ]; then
+                    PATH=$PATH:$1
+                else
+                    PATH=$1:$PATH
+                fi
             fi
-        fi
-        ;;
+            ;;
     esac
 }
 
-pathmungex() {
-    # like pathmunge, but better
+pathmungex()
+{
+    : 'like pathmunge, but better'
     local params arg PATHVAR DIR EXPORT AFTER HELP
     params=(PATHVAR DIR)
     while [[ $# -gt 0 ]]; do
         arg="$1"
         shift
         case $arg in
-        -e | --export) EXPORT=1 ;;
-        -a | --after) AFTER=1 ;;
-        -h | --help) HELP=1 ;;
-        -*)
-            echo >&2 "[X] I don't understand \"$arg\""
-            HELP=1
-            ;;
-        *)
-            : "setting a positional parameter: ${params[0]} -> $arg"
-            if [[ ${#params[@]} -gt 0 ]]; then
-                param="${params[0]}"
-                declare "$param=$arg"
-                params=("${params[@]:1}")
-            else
-                echo >&2 "[X] Too many parameters: \"$arg\""
+            -e | --export) EXPORT=1 ;;
+            -a | --after) AFTER=1 ;;
+            -h | --help) HELP=1 ;;
+            -*)
+                echo >&2 "[X] pathmungex: I don't understand \"$arg\""
                 HELP=1
-            fi
-            ;;
+                ;;
+            *)
+                : "setting a positional parameter: ${params[0]} -> $arg"
+                if [[ ${#params[@]} -gt 0 ]]; then
+                    param="${params[0]}"
+                    declare "$param=$arg"
+                    params=("${params[@]:1}")
+                else
+                    echo >&2 "[X] pathumngex: Too many parameters: \"$arg\""
+                    HELP=1
+                fi
+                ;;
         esac
     done
 
     if [[ ${#params[@]} -gt 0 ]]; then
-        echo >&2 "[X] Not enough parameters"
+        echo >&2 "[X] pathumngex: Not enough parameters"
         HELP=1
     fi
 
@@ -155,47 +248,50 @@ pathmungex() {
             declare -g "$PATHVAR=$DIR:${!PATHVAR}"
         fi
         if [[ -v EXPORT ]]; then
-            export $PATHVAR
+            export "${PATHVAR?}"
         fi
     fi
 }
 
-showmounts() {
-    # list mounts in a table, and cut off the options
+showmounts()
+{
+    : 'list mounts in a table, and cut off the options'
     mount -l "$@" | cut -d "(" -f 1 | sed -r "s/\<(on|type)\>/% \0/g" | column -t -s %
 }
 
-flash_message() {
+flash_message()
+{
+    : 'breifly print a message to the screen'
     local arg message HELP
     local sleep=1
     while [[ $# -gt 0 ]]; do
         arg="$1"
         shift
         case $arg in
-        -s | --sleep)
-            sleep="$1"
-            shift
-            ;;
-        -h | --help)
-            HELP=1
-            ;;
-        -*)
-            echo >&2 "Unrecognized option: $arg"
-            ;;
-        *)
-            message+="$arg "
-            ;;
+            -s | --sleep)
+                sleep="$1"
+                shift
+                ;;
+            -h | --help)
+                HELP=1
+                ;;
+            -*)
+                echo >&2 "Unrecognized option: $arg"
+                ;;
+            *)
+                message+="$arg "
+                ;;
         esac
     done
 
     if [[ -v HELP ]]; then
-        command cat <<EOF
-flash_message: briefly print a message to the screen.
+        command cat <<-EOF
+		flash_message: briefly print a message to the screen.
 
-Usage: flash_message [-s|--sleep SLEEP] MESSAGE...
+		Usage: flash_message [-s|--sleep SLEEP] MESSAGE...
 
-	-s|--sleep: how long to sleep (currently $sleep)
-EOF
+			-s|--sleep: how long to sleep (currently $sleep)
+		EOF
         return 1
     fi
 
@@ -206,7 +302,8 @@ EOF
     tput ed
 }
 
-# function vim() {
+# vim()
+# {
 #     flash_message -s 2 '!!! use nv !!!'
 #     nvim "$@"
 #     return $?
@@ -215,17 +312,21 @@ EOF
 # don't wanna set pager globally, but do wanna pick one for these
 doihave bat && _pager=bat || _pager=less
 
-# mnemonic: `jq | less`
-function jql() {
+jql()
+{
+    : 'mnemonic: `jq | less`'
     jq -C "${@:-.}" | $_pager
 }
 
-# mnemonic: `jq | less`
-function yql() {
+yql()
+{
+    : 'mnemonic: `yq | less`'
     yq -C "${@:-.}" | $_pager
 }
 
-pkg-config-vars() {
+pkg-config-vars()
+{
+    : 'display all pkg-config variables for a name'
     for name in "$@"; do
         pkg-config "$name" --print-variables | while read -r var; do
             value=$(pkg-config "$name" --variable "$var")
@@ -234,13 +335,180 @@ pkg-config-vars() {
     done
 }
 
-pkg-config-names() {
-    pkg-config --list-all | cut -f1 -d" "
+pkg-config-names()
+{
+    pkg-config --list-all | cut -f1 -d" " | sort
 }
 
-_complete-pkg-config-names() {
-    COMPREPLY=($(compgen -W "$(pkg-config-names)" -- "${COMP_WORDS[COMP_CWORD]}"))
-    return 0
+_complete-pkg-config-names()
+{
+    # mapfile -t COMPREPLY < <(compgen -W "$(pkg-config-names)" -- "${COMP_WORDS[COMP_CWORD]}")
+    get_array COMPREPLY -- compgen -W "$(pkg-config-names)" -- "${COMP_WORDS[COMP_CWORD]}"
 }
 
 complete -F _complete-pkg-config-names pkg-config-vars
+
+dush()
+{
+    : 'like alias dush=`du -shxc`'
+    command du -shxc "$@" | sort -h
+}
+
+dfh()
+{
+    : 'like alias dfh=`df -hT -t xfs -t ext4`'
+    df -hT -t xfs -t ext4 "$@" | sort -h -k 4
+}
+
+each()
+{
+    for item in "$@"; do
+        echo "$item"
+    done
+}
+
+showpaths()
+{
+    : 'pretty print pathlike variables'
+    : 'usage: showpaths [PATHVAR...]'
+    status=0
+
+    # make a list of parameters, defaulting to just "PATH"
+    paths=("${@:-PATH}")
+
+    for item in "${paths[@]}"; do
+        if [[ ! -v $item ]]; then
+            # if there's no variable with that name, warn & continue
+            echo >&2 "[X] showpaths: $item unset"
+            status=1
+            continue
+        fi
+
+        # if more than one argument, print a header
+        [[ ${#paths[@]} -gt 1 ]] && echo "===== $item ====="
+        # echo path variable contents, one per line
+        echo "${!item}" | tr : "\n"
+    done
+    return $status
+}
+complete -v showpaths
+
+searchpath()
+{
+    : 'search a pathlike variable'
+    : 'usage: searchpath PATHVAR name [name...]'
+
+    [[ $# -lt 2 ]] && return 1
+
+    pathvar="$1"
+    shift
+    names=("$@")
+
+    if [[ ! -v $pathvar ]]; then
+        # if there's no variable with that name, explode
+        echo >&2 "[X] searchpath: $pathvar unset"
+        return 1
+    fi
+
+    # read contents of variable named by `pathvar` into array, separated by colons
+    mapfile -td: pathlist <<< "${!pathvar}"
+
+    for path in "${pathlist[@]}"; do
+        for name in "${names[@]}"; do
+            # expand any globs & print existing files
+            compgen -G "$path/$name"
+        done
+    done
+
+}
+complete -v searchpath
+
+fatal()
+{
+    : 'display an error with an optional message; stacktrace; exit 1'
+    echo >&2 "[X] ${*:-Fatal Error}"
+    stacktrace
+    exit 1
+}
+
+stacktrace()
+{
+    : 'print the current call stack'
+    local idx filename subroutine lineno context lines ctx_lineno prefix
+
+    context=2
+    top=1
+    bottom=1
+
+    local opt OPTARG OPTIND help
+    while getopts :hc:t:b: opt; do
+        case $opt in
+            h)
+                help=1
+                ;;
+            c)
+                context=$OPTARG
+                ;;
+            t)
+                top=$OPTARG
+                ;;
+            b)
+                bottom=$OPTARG
+                ;;
+            :)
+                echo >&2 "[X] stacktrace: required argument not found: $OPTARG"
+                help=1
+                ;;
+            ?)
+                echo >&2 "[X] stacktrace: invalid option: $OPTARG"
+                help=1
+                ;;
+            *)
+                echo >&2 "[X] stacktrace: unexpected input"
+                declare -p opt OPTARG
+                help=1
+                ;;
+        esac
+    done
+    shift $((OPTIND - 1))
+
+    if [[ -v help ]]; then
+        cat >&2 << EOF
+${FUNCNAME[0]}: print a bash function stacktrace
+Usage: ${FUNCNAME[0]} [-h] [-c CONTEXT] [-b BOTTOM] [-t TOP]
+
+Options:
+-c CONTEXT      print CONTEXT number of lines of context (currently $context)
+-b BOTTOM       trim BOTTOM frames from the bottom of the stack (currently $bottom)
+-t TOP          trim TOP frames from the top of the stack (currently $top)
+EOF
+        return 1
+    fi
+
+    echo "  Call stack (starting with oldest frame):"
+    # iterating through 3 related arrays in reverse; -1 for array end ; idx > 0 to skip this function
+    for ((idx = ${#BASH_SOURCE[@]} - bottom; idx >= top; idx--)); do
+        filename=${BASH_SOURCE[$idx]}
+        subroutine=${FUNCNAME[$idx]}
+        lineno=${BASH_LINENO[$idx - 1]}
+
+        unset lines
+        # read into array $lines from $filename at $lineno
+        # (such that $index = $lineno) with $context surrounding lines
+        mapfile -s $((lineno - context - 1)) -O $((lineno - context)) -n $((context * 2 + 1)) -t lines < "$filename"
+
+        echo "    $filename($subroutine):"
+        for ctx_lineno in "${!lines[@]}"; do
+            ((ctx_lineno == lineno)) && prefix="   >>" || prefix="     "
+            echo "$prefix $ctx_lineno ${lines[$ctx_lineno]}"
+        done
+
+    done
+}
+
+faketty()
+{
+    : 'convince a command that it is attached to a tty'
+    script -qefc "$(printf "%q " "$@")" /dev/null
+}
+complete -c faketty
diff --git a/dotfiles/bashrc b/dotfiles/bashrc
--- a/dotfiles/bashrc
+++ b/dotfiles/bashrc
@@ -31,6 +31,13 @@ export PIPENV_VENV_IN_PROJECT=1
 export DOCKER_HIDE_LEGACY_COMMANDS=1
 export DOCKER_BUILDKIT=1
 export EDITOR=vim
+export PAGER=less
+
+# attempt to set some options for LESS LESS="-SRFXJ"
+export LESS="-SRFi"
+# (less --mouse |& grep -q "no mouse option") || LESS+=" --mouse --wheel-lines=3"
+(less --help |& grep -q "mouse") && LESS+=" --mouse --wheel-lines=3"
+export LESSCHARSET=utf-8
 
 # [[ -x $HOME/.local/bin/vim ]] && export EDITOR=$HOME/.local/bin/vim
 # [[ -x $HOME/.local/bin/less ]] && export PAGER=$HOME/.local/bin/less
@@ -47,6 +54,7 @@ LOCAL_BASH_COMPLETION=/usr/local/share/bash-completion/bash_completion
 [[ -f $HOME/.bash_functions ]] && . "$HOME/.bash_functions"
 
 # counter-intuitively, later lines will be higher in the path
+pathmungex PATH "/usr/local/go/bin"
 pathmungex PATH "$HOME/.local/share/node/bin"
 pathmungex PATH "$HOME/.local/share/flyway"
 pathmungex PATH "$HOME/.local/share/groovy/bin"
@@ -61,21 +69,12 @@ pathmungex PATH "$HOME/.nodenv/bin"
 pathmungex PATH "$HOME/.tfenv/bin"
 pathmungex PATH "$HOME/.tgenv/bin"
 pathmungex PATH "$HOME/.bin"
-pathmungex PATH "$HOME/.maxar-bin"
 
-# pathmungex --after PATH $HOME/.bootstrap/bin
-# pathmungex --after PATH $HOME/.bootstrap/java/default/bin
-# pathmungex --after PATH $HOME/.bootstrap/maven/default/bin
-# pathmungex --after PATH $HOME/.bootstrap/gradle/default/bin
-# pathmungex --after PATH $HOME/.bootstrap/miniconda/bin
-
-pathmungex --after PATH /usr/pgsql-12/bin
-
-export PERL_MB_OPT="--install_base /home/tbozeman/perl5"
-export PERL_MM_OPT="INSTALL_BASE=/home/tbozeman/perl5"
-pathmungex PATH /home/tbozeman/perl5/bin
-pathmungex -e -a PERL_LOCAL_LIB_ROOT "$HOME/perl5"
-pathmungex -e PERL5LIB "$HOME/perl5/lib/perl5"
+# export PERL_MB_OPT="--install_base $HOME/perl5"
+# export PERL_MM_OPT="INSTALL_BASE=$HOME/perl5"
+# pathmungex PATH "$HOME/perl5/bin"
+# pathmungex -e -a PERL_LOCAL_LIB_ROOT "$HOME/perl5"
+# pathmungex -e PERL5LIB "$HOME/perl5/lib/perl5"
 
 pathmungex -e PYTHONPATH "$HOME/.pymodules"
 
@@ -102,51 +101,39 @@ HISTCONTROL=ignoreboth
 shopt -s histappend
 
 # for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
-HISTSIZE=
-HISTFILESIZE=
-HISTTIMEFORMAT="%h %d %H:%M:%S> "
+# bash 4.2 doesn't seem to like negative values here...
+# HISTSIZE="-1"
+# HISTFILESIZE="-1"
+HISTSIZE=$((2 ** 20))
+HISTFILESIZE=$HISTSIZE
 HISTIGNORE="ls:la:lf:ll:l"
+# HISTTIMEFORMAT="%h %d %H:%M:%S> "
+HISTTIMEFORMAT="%Y-%m-%d %H:%M:%S> "
 
 # check the window size after each command and, if necessary,
 # update the values of LINES and COLUMNS.
 shopt -s checkwinsize
-
-# use a specific key for rsync over ssh
-export RSYNC_RSH="ssh -i $HOME/.ssh/rsync_key"
-
 # set autocd: if command is a directory, cd to it
 shopt -s autocd
 # set recursive globbing w/ "**"
 shopt -s globstar
-
-# attempt to set some options for LESS LESS="-SRFXJ"
-export LESS="-SRFi"
-# (less --mouse |& grep -q "no mouse option") || LESS+=" --mouse --wheel-lines=3"
-(less --help |& grep -q "mouse") && LESS+=" --mouse --wheel-lines=3"
+# I wanna set this, but it seems like it would probably break things...
+# shopt -s nocaseglob
+# if any command in a pipeline fails, the pipeline should be considered to have failed
+shopt -so pipefail
 
 # these have been written to disk in order to reduce bash startup time. the
 # bash completion ones are in ~/.local/share/bash-completion/completions and
 # are lazily loaded at first use
 
-doihave kubectl && eval "$(kubectl completion bash)"
-doihave helm && eval "$(helm completion bash)"
-doihave kind && eval "$(kind completion bash)"
+# doihave kubectl && eval "$(kubectl completion bash)"
+# doihave helm && eval "$(helm completion bash)"
+# doihave kind && eval "$(kind completion bash)"
 # doihave poetry && eval "$(poetry completions bash)"
 # doihave pipenv && eval "$(_PIPENV_COMPLETE=bash_source pipenv)"
 # doihave oc && eval "$(oc completion bash)"
 # doihave yq && eval "$(yq shell-completion bash)"
 
-export SDKMAN_DIR="$HOME/.sdkman"
-[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"
-
-export NVM_DIR="$HOME/.nvm"
-[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
-[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
-
-# [ -z $SSH_AUTH_SOCK ] && eval $(ssh-agent -s) >/dev/null 2>&1
-
-# export M2_HOME=/home/tbozeman/.bootstrap/maven/default
-# export JAVA_HOME=$HOME/.bootstrap/java/default
 
 # When set to "1" suggest all commands, including plumbing commands
 # which are hidden by default (e.g. "cat-file" on "git ca<TAB>").
@@ -176,15 +163,19 @@ export DOCKER_COMPLETION_SHOW_PLUGIN_IDS=yes
 export DOCKER_COMPLETION_SHOW_SECRET_IDS=yes
 export DOCKER_COMPLETION_SHOW_SERVICE_IDS=yes
 
-pathmungex -e PKG_CONFIG_PATH "$HOME/local/lib/pkgconfig"
-pathmungex -e PKG_CONFIG_PATH "$HOME/local/lib64/pkgconfig"
-pathmungex -e PKG_CONFIG_PATH "$HOME/local/share/pkgconfig"
-pathmungex -e PKG_CONFIG_PATH /usr/local/lib/pkgconfig
-pathmungex -e PKG_CONFIG_PATH /usr/local/lib64/pkgconfig
-pathmungex -e PKG_CONFIG_PATH /usr/local/share/pkgconfig
+# export PKG_CONFIG_PATH
+# pathmungex PKG_CONFIG_PATH /usr/share/pkgconfig
+# pathmungex PKG_CONFIG_PATH /usr/lib64/pkgconfig
+# pathmungex PKG_CONFIG_PATH /usr/lib/pkgconfig
+# pathmungex PKG_CONFIG_PATH /usr/local/share/pkgconfig
+# pathmungex PKG_CONFIG_PATH /usr/local/lib64/pkgconfig
+# pathmungex PKG_CONFIG_PATH /usr/local/lib/pkgconfig
+# pathmungex PKG_CONFIG_PATH "$HOME/local/share/pkgconfig"
+# pathmungex PKG_CONFIG_PATH "$HOME/local/lib64/pkgconfig"
+# pathmungex PKG_CONFIG_PATH "$HOME/local/lib/pkgconfig"
 
 for item in ~/.profile.d/*.{sh,bash}; do
-    [[ -f $item && -r $item ]] && . $item
+    [[ -f $item && -r $item ]] && . "$item"
 done
 unset item
 
diff --git a/dotfiles/bin/taskify b/dotfiles/bin/taskify
--- a/dotfiles/bin/taskify
+++ b/dotfiles/bin/taskify
@@ -12,57 +12,58 @@
 # - output only on error
 # - logrotate?
 
-die() {
-	echo "taskify: $@"
-	[[ $LOG ]] && echo "taskify: $@" >>$LOG
-	exit 1
+die()
+{
+    echo "taskify: $*"
+    [[ $LOG ]] && echo "taskify: $*" >> "$LOG"
+    exit 1
 }
 
 while [[ $# -gt 0 ]]; do
-	arg="$1"
-	shift
-	case $arg in
-	--) break ;;
-	-h | --help)
-		HELP=1
-		;;
-	-s | --random-sleep)
-		TIMEOUT="$1"
-		shift
-		;;
-	-q | --quiet)
-		QUIET=$((${QUIET:-0} + 1))
-		;;
-	-l | --log)
-		LOG="$1"
-		shift
-		;;
-	-d | --directory)
-		DIRECTORY="$1"
-		shift
-		;;
-	-*)
-		echo "[X] I don't understand this argument: ($arg)"
-		HELP=1
-		;;
-	*)
-		# put this arg back on the stack
-		set -- "$arg" "$@"
-		break
-		;;
-	esac
+    arg="$1"
+    shift
+    case $arg in
+        --) break ;;
+        -h | --help)
+            HELP=1
+            ;;
+        -s | --random-sleep)
+            TIMEOUT="$1"
+            shift
+            ;;
+        -q | --quiet)
+            QUIET=$((${QUIET:-0} + 1))
+            ;;
+        -l | --log)
+            LOG="$1"
+            shift
+            ;;
+        -d | --directory)
+            DIRECTORY="$1"
+            shift
+            ;;
+        -*)
+            echo "[X] I don't understand this argument: ($arg)"
+            HELP=1
+            ;;
+        *)
+            # put this arg back on the stack
+            set -- "$arg" "$@"
+            break
+            ;;
+    esac
 done
 
 COMMAND=("$@")
 
 if [[ ! $HELP && ! "${COMMAND[*]}" ]]; then
-	echo "[X] No command supplied"
-	HELP=1
+    echo "[X] No command supplied"
+    HELP=1
 fi
 
 if [[ $HELP ]]; then
-	cat <<EOF
-Usage: $(basename $0) [OPTIONS] [--] COMMAND ...
+    cat << EOF
+Usage: $(basename "$0") [OPTIONS] [--] COMMAND ...
 
 Sanitize commands for cron.
 
@@ -72,7 +73,7 @@ COMMAND                 The command to run, with arguments
 Options:
 -h|--help       Print out this message.
 -q|--quiet      Silence the command, unless it exits with an error (to prevent
-                useless cron emails from chatty programs). Can be given more 
+                useless cron emails from chatty programs). Can be given more
                 than once to also silence errors
 -l|--log LOG    Append any output to LOG as well (includes timestamp & exit
                 code; path LOG is *not* relative to --directory argument)
@@ -84,35 +85,35 @@ Options:
                 change to DIRECTORY before executing command
 EOF
 
-	exit 1
+    exit 1
 fi
 
 if [[ $TIMEOUT ]]; then
-	sleep $((RANDOM % TIMEOUT))
+    sleep $((RANDOM % TIMEOUT))
 fi
 
 if [[ $DIRECTORY ]]; then
-	pushd $DIRECTORY &>/dev/null || die "could not change directory to ($DIRECTORY)"
+    pushd "$DIRECTORY" &> /dev/null || die "could not change directory to ($DIRECTORY)"
 fi
 
-output="$(eval "${COMMAND[@]}" 2>&1)"
+output=$("${COMMAND[@]}" 2>&1)
 status=$?
 
 if [[ $DIRECTORY ]]; then
-	popd &>/dev/null
+    popd &> /dev/null || die "could return to starting directory"
 fi
 
 if [[ ! $QUIET || ($QUIET -lt 2 && $status -ne 0) ]]; then
-	[[ $output ]] && echo "$output"
+    [[ $output ]] && echo "$output"
 fi
 
 if [[ $LOG ]]; then
-	[[ $output ]] || output='(no output)'
-	{
-		date
-		echo "$output"
-		echo "exit code $status"
-	} >>$LOG
+    [[ $output ]] || output='(no output)'
+    {
+        date
+        echo "$output"
+        echo "exit code $status"
+    } >> "$LOG"
 fi
 
 exit $status
diff --git a/dotfiles/bin/use-pyenv b/dotfiles/bin/use-pyenv
--- a/dotfiles/bin/use-pyenv
+++ b/dotfiles/bin/use-pyenv
@@ -11,47 +11,47 @@ VERSIONS=()
 COMMAND=()
 
 while [[ $# -gt 0 ]]; do
-	arg="$1"
-	shift
-	case $arg in
-	--)
-		COMMAND=("$@")
-		break
-		;;
-	-d | --default)
-		DEFAULT=1
-		unset LATEST
-		;;
-	-l | --latest)
-		LATEST=1
-		unset DEFAULT
-		;;
-	-*)
-		echo >&2 "[X] Unrecognized argument: $arg"
-		HELP=1
-		break
-		;;
-	*)
-		VERSIONS+=("$arg")
-		;;
-	esac
+    arg="$1"
+    shift
+    case $arg in
+        --)
+            COMMAND=("$@")
+            break
+            ;;
+        -d | --default)
+            DEFAULT=1
+            unset LATEST
+            ;;
+        -l | --latest)
+            LATEST=1
+            unset DEFAULT
+            ;;
+        -*)
+            echo >&2 "[X] Unrecognized argument: $arg"
+            HELP=1
+            break
+            ;;
+        *)
+            VERSIONS+=("$arg")
+            ;;
+    esac
 done
 
 if [[ ${#VERSIONS[@]} -eq 0 && ! -v LATEST && ! -v DEFAULT ]]; then
-	echo >&2 "[X] No version given"
-	HELP=1
+    echo >&2 "[X] No version given"
+    HELP=1
 fi
 
 if [[ ${#COMMAND[@]} -eq 0 && ! -v HELP ]]; then
-	echo >&2 "[X] No command given"
-	HELP=1
+    echo >&2 "[X] No command given"
+    HELP=1
 fi
 
 if [[ -v HELP ]]; then
-	echo <<EOF
-$(basename $0): execute a command with a particular pyenv VERSION
+    cat << EOF
+$(basename "$0"): execute a command with a particular pyenv VERSION
 
-Usage: $(basename $0) (VERSION...|--latest|--default) -- COMMAND...
+Usage: $(basename "$0") (VERSION...|--latest|--default) -- COMMAND...
 
 Options:
 
@@ -60,39 +60,39 @@ VERSION         one or more python version numbers, in order of preference
 -d, --default   let pyenv select a version
 COMMAND         a command to be executed in the context of a given python version
 EOF
-	exit 1
+    exit 1
 fi
 
-: ${PYENV_ROOT:=$HOME/.pyenv}
+: "${PYENV_ROOT:=$HOME/.pyenv}"
 [[ :$PATH: == *:$PYENV_ROOT/bin:* ]] || PATH=$PYENV_ROOT/bin:$PATH
 [[ :$PATH: == *:$PYENV_ROOT/shims:* ]] || PATH=$PYENV_ROOT/shims:$PATH
 
-if (! command -v pyenv &>/dev/null); then
-	echo >&2 "[X] pyenv not found"
-	echo $PATH | tr : "\n"
-	exit 1
+if (! command -v pyenv &> /dev/null); then
+    echo >&2 "[X] pyenv not found"
+    echo "$PATH" | tr : "\n"
+    exit 1
 fi
 
 if [[ -v LATEST ]]; then
-	VERSIONS=(
-		$(
-			pyenv versions --bare --skip-envs --skip-aliases |
-				grep -E '^[0-9]+\.[0-9]+(\.[0-9]+)?$' |
-				sort -Vr |
-				head -n 1
-		)
-		"${VERSIONS[@]}"
-	)
+    VERSIONS=(
+        "$(
+            pyenv versions --bare --skip-envs --skip-aliases |
+                grep -E '^[0-9]+\.[0-9]+(\.[0-9]+)?$' |
+                sort -Vr |
+                head -n 1
+        )"
+        "${VERSIONS[@]}"
+    )
 elif [[ -v DEFAULT ]]; then
-	VERSIONS=(${PYENV_VERSION:-} "${VERSIONS[@]}")
+    VERSIONS=("${PYENV_VERSION:-}" "${VERSIONS[@]}")
 fi
 
 VERSION_STRING=$(
-	IFS=:
-	echo "${VERSIONS[*]}"
+    IFS=:
+    echo "${VERSIONS[*]}"
 )
 
-exec env PYENV_VERSION=$VERSION_STRING pyenv exec "${COMMAND[@]}"
+exec env PYENV_VERSION="$VERSION_STRING" pyenv exec "${COMMAND[@]}"
 
 # export PYENV_VERSION=$VERSION_STRING
 # exec pyenv exec "${COMMAND[@]}"
diff --git a/dotfiles/maxar-bin/eureka b/dotfiles/maxar-bin/eureka
--- a/dotfiles/maxar-bin/eureka
+++ b/dotfiles/maxar-bin/eureka
@@ -1,50 +1,64 @@
 #!/bin/bash
 
-trap 'echo >&2 "[!] eureka: got ($?) on line $LINENO: $BASH_COMMAND"' ERR
-
 set -eEuo pipefail
+trap 'echo >&2 "[!] got ($?) on line $LINENO: $BASH_COMMAND"' ERR
 
 while [[ $# -gt 0 ]]; do
-    arg="$1" ; shift
+    arg="$1"
+    shift
     case $arg in
-        (-h|--help)
-            HELP=1 ;;
-        (-v|--verbose)
-            VERBOSE=1 ;;
-        (-m|--multi|--multiple)
-            MULTI=1 ;;
-        (--no-multi|--no-multiple)
-            unset MULTI ;;
-        (-e|--env|--environ|--environment)
-            ENVIRONMENT=$1 ; shift ;;
-        (-d|--dump)
-            DUMP=1 ;;
-        (--no-dump)
-            unset DUMP ;;
-        (-s|--suggest)
-            MAKE_SUGGESTIONS=1 ;;
-        (-S|--services?)
-            MAKE_SERVICE=1 ;;
-        (--no-suggest)
-            unset MAKE_SUGGESTIONS ;;
-        (-f|--field)
-            FIELD=$1 ; shift ;;
-        (-*)
+        -h | --help)
+            HELP=1
+            ;;
+        -v | --verbose)
+            VERBOSE=1
+            ;;
+        -m | --multi | --multiple)
+            MULTI=1
+            ;;
+        --no-multi | --no-multiple)
+            unset MULTI
+            ;;
+        -e | --env | --environ | --environment)
+            ENVIRONMENT=$1
+            shift
+            ;;
+        -d | --dump)
+            DUMP=1
+            ;;
+        --no-dump)
+            unset DUMP
+            ;;
+        -s | --suggest)
+            MAKE_SUGGESTIONS=1
+            ;;
+        -S | --services?)
+            MAKE_SERVICE=1
+            ;;
+        --no-suggest)
+            unset MAKE_SUGGESTIONS
+            ;;
+        -f | --field)
+            FIELD=$1
+            shift
+            ;;
+        -*)
             echo >&2 "I don't understand this argument: $arg"
             HELP=1
             ;;
-        (*)
-            SERVICES+=( "$arg" ) ;;
+        *)
+            SERVICES+=("$arg")
+            ;;
     esac
 done
 
 if [[ -v HELP || ! -v SERVICES ]]; then
-    cat >&2 <<EOF
-$(basename $0): look up maxar services via eureka
+    cat >&2 << EOF
+$(basename "$0"): look up maxar services via eureka
 
-Usage: $(basename $0) [-h|--help] [(-e|--env|--environment) ENV] SERVICE...
+Usage: $(basename "$0") [-h|--help] [(-e|--env|--environment) ENV] SERVICE...
 
-General Options: 
+General Options:
 
 -h|--help       This help output.
 -s|--suggest    suggest other possible service names when none are found
@@ -70,69 +84,92 @@ fi
 [[ -v EUREKA_SERVER_URL && -v SERVICE_DISCOVERY_MAP ]] || . ~/.ssh/P2020
 
 if [[ -v ENVIRONMENT ]]; then
-    try_url="$( jq -re --arg env $ENVIRONMENT '.[$env]?' <<< $SERVICE_DISCOVERY_MAP )" \
-        && EUREKA_SERVER_URL=$try_url \
-        || { echo >&2 "[!] could not match environment '$ENVIRONMENT'" ; true ; }
+    if try_url="$(jq -re --arg env "$ENVIRONMENT" '.[$env]?' <<< "$SERVICE_DISCOVERY_MAP")"; then
+        EUREKA_SERVER_URL=$try_url
+    else
+        echo >&2 "[!] could not match environment '$ENVIRONMENT'"
+    fi
 fi
 
-
-build_service_url() {
-    # we'll read a json payload from stdin
+build_service_url()
+{
+    : 'read one or more service json payloads from stdin & output a service url for each'
     jq -r '"service://\(.app | ascii_downcase)/\(.metadata.version)/\(.metadata.environment)"'
 }
 
-fail() {
+fail()
+{
+    : 'die, potentially emitting some service name suggestions'
     [[ -v MAKE_SUGGESTIONS ]] && make_suggestions
     exit 1
 }
 
-make_suggestions() {
+make_suggestions()
+{
+    : 'extract all found service urls & emit them as suggestions'
     echo >&2 "[!] service not found; perhaps one of these?"
     build_service_url <<< "$original" >&2
 }
 
+split_service()
+{
+    : 'split a service into parts; accepts http urls, service urls, and bare service names'
+    : 'creates no output; sets `service_*` variables'
+    local IFS=/
+    read -r service_proto _ service_name service_vers service_env service_path <<< "$1"
+    if [[ -z $service_name ]]; then
+        service_name=$service_proto
+    fi
+}
+
 for service in "${SERVICES[@]}"; do
 
-    if grep -q '^service://' <<< $service ; then
-        # in the form of "service://ancillary-image-tracker-backend-v2/1.0/devint-us-east-1/events"
-        service_name=$( cut -d/ -f3 <<< $service )
-        service_vers=$( cut -d/ -f4 <<< $service )
-        service_env=$( cut -d/ -f5 <<< $service )
-        service_path=$( cut -d/ -f6- <<< $service )
-    else
-        # assumed to be a bare service name
-        service_name=$service
-        service_vers=
-        service_env=
-        service_path=
-    fi
+    # if grep -q '^service://' <<< "$service"; then
+    #     # in the form of "service://ancillary-image-tracker-backend-v2/1.0/devint-us-east-1/events"
+    #     service_name=$(cut -d/ -f3 <<< "$service")
+    #     service_vers=$(cut -d/ -f4 <<< "$service")
+    #     service_env=$(cut -d/ -f5 <<< "$service")
+    #     service_path=$(cut -d/ -f6- <<< "$service")
+    # else
+    #     # assumed to be a bare service name
+    #     service_name=$service
+    #     service_vers=
+    #     service_env=
+    #     service_path=
+    # fi
+
+    split_service "$service"
 
     # hit the eureka server itself, & get json payload for our service name
-    payload="$( curl -Ssf -H "Accept: application/json" "$EUREKA_SERVER_URL/eureka/apps/$service_name" )" || {
+    payload="$(curl -Ssf -H "Accept: application/json" "$EUREKA_SERVER_URL/eureka/apps/$service_name")" || {
         echo >&2 "[!] error caught while looking up '$service'"
         exit 1
     }
 
     # first unwrap
-    payload="$( jq -c '.application.instance[]?' <<< "$payload" )"
+    payload="$(jq -c '.application.instance[]?' <<< "$payload")"
     # save a copy for finding suggestions
     original="$payload"
 
     if [[ -v DUMP ]]; then
-        jq . <<< $payload
+        jq . <<< "$payload"
     else
-        # turn our version number $(potentially w/ shell wildcards) into a regex, kinda
-        service_vers="^$( sed 's/\*/.*/g' <<< $service_vers | sed 's/\./\\./g' )"
+        # turn our version number (potentially w/ shell wildcards) into a regex, kinda
+        service_vers="^$(sed -r -e 's/\./\\./g' -e 's/\*/.*/g' <<< "$service_vers")"
         # filter based on that version number
-        [[ $service_vers ]] && { payload="$( jq -sce --arg vers "$service_vers" '.[] | select( .metadata.version | try tostring catch "" | test( $vers ))' <<< "$payload" )" || fail ; }
+        [[ $service_vers ]] && {
+            payload="$(jq -sce --arg vers "$service_vers" '.[] | select( .metadata.version | try tostring catch "" | test( $vers ))' <<< "$payload")" || fail
+        }
         # clean up our service environment
         [[ $service_env =~ ^(dev|int|devint|reg|prod|ft)$ ]] && service_env="${service_env}-us-east-1"
         # filter by that, if it exists
-        [[ $service_env ]] && { payload="$( jq -sce --arg env "$service_env" '.[] | select( .metadata.environment == $env )' <<< "$payload" )" || fail ; }
+        [[ $service_env ]] && {
+            payload="$(jq -sce --arg env "$service_env" '.[] | select( .metadata.environment == $env )' <<< "$payload")" || fail
+        }
         # sort instances by version number (highest to lowest)
-        payload="$( jq -sce 'sort_by([.metadata.version // "" | split(".")[] | try tonumber catch 0]) | reverse[]' <<< "$payload" )"
+        payload="$(jq -sce 'sort_by([.metadata.version // "" | split(".")[] | try tonumber catch 0]) | reverse[]' <<< "$payload")"
         # potentially take the top one
-        [[ -v MULTI ]] || payload="$( jq -sce '.[0]' <<< "$payload" )"
+        [[ -v MULTI ]] || payload="$(jq -sce '.[0]' <<< "$payload")"
         # and display
         if [[ -v VERBOSE ]]; then
             jq -e . <<< "$payload"
diff --git a/dotfiles/maxar-bin/list-subscriptions b/dotfiles/maxar-bin/list-subscriptions
--- a/dotfiles/maxar-bin/list-subscriptions
+++ b/dotfiles/maxar-bin/list-subscriptions
@@ -2,69 +2,70 @@
 # vim: tw=0
 
 set -eEuo pipefail
-trap 'echo "err ($?) at ($BASH_SOURCE:$LINENO): $BASH_COMMAND"' ERR
+trap 'echo >&2 "err ($?) at ($BASH_SOURCE:$LINENO): $BASH_COMMAND"' ERR
 
 while [[ $# -gt 0 ]]; do
-	arg="$1"
-	shift
-	case $arg in
-	-*=*)
-		# split --var=value pairs into separate tokens
-		# but only replacing the first '='!
-		set -- $(echo $arg | sed 's/=/ /') "$@"
-		;;
-	-d | --dump)
-		DUMP=1
-		;;
-	-v | --verbose)
-		VERBOSE=1
-		unset DUMP NAMES LINKS
-		;;
-	-q | --quiet)
-		QUIET=1
-		;;
-	-n | --names)
-		NAMES=1
-		unset DUMP VERBOSE LINKS
-		;;
-	-l | --links)
-		LINKS=1
-		unset DUMP VERBOSE NAMES
-		;;
-	-m | --match-name)
-		PATTERN="$1"
-		shift
-		unset DUMP IDENTITY
-		;;
-	-i | --identity)
-		IDENTITY="$1"
-		shift
-		unset DUMP PATTERN
-		;;
-	--delete)
-		# intentionally not unsetting `DUMP` here
-		DELETE=1
-		;;
-	-h | --help)
-		HELP=1
-		;;
-	*)
-		echo "I don't understand '$arg'"
-		USAGE=1
-		;;
-	esac
+    arg="$1"
+    shift
+    case $arg in
+        -*=*)
+            # split --var=value pairs into separate tokens
+            # but only replacing the first '='!
+            # set -- $(echo $arg | sed 's/=/ /') "$@"
+            set -- ${arg/=/ } "$@"
+            ;;
+        -d | --dump)
+            DUMP=1
+            ;;
+        -v | --verbose)
+            VERBOSE=1
+            unset DUMP NAMES LINKS
+            ;;
+        -q | --quiet)
+            QUIET=1
+            ;;
+        -n | --names)
+            NAMES=1
+            unset DUMP VERBOSE LINKS
+            ;;
+        -l | --links)
+            LINKS=1
+            unset DUMP VERBOSE NAMES
+            ;;
+        -m | --match-name)
+            PATTERN="$1"
+            shift
+            unset DUMP IDENTITY
+            ;;
+        -i | --identity)
+            IDENTITY="$1"
+            shift
+            unset DUMP PATTERN
+            ;;
+        --delete)
+            # intentionally not unsetting `DUMP` here
+            DELETE=1
+            ;;
+        -h | --help)
+            HELP=1
+            ;;
+        *)
+            echo "I don't understand '$arg'"
+            USAGE=1
+            ;;
+    esac
 done
 
 if [[ -v USAGE || -v HELP ]]; then
-	cat <<EOF
+    cat << EOF
 List event serivice subscriptions. By default, find subscriptions matching our
 client ID (per ~/.ssh/P2020), and output subscription urls.
-Usage: $(basename $0) [-h|--help] [OPTIONS]
+Usage: $(basename "$0") [-h|--help] [OPTIONS]
 EOF
 fi
 
 if [[ -v HELP ]]; then
-	cat <<EOF
+    cat << EOF
 
 Options:
 
@@ -89,58 +90,58 @@ EOF
 fi
 
 if [[ -v USAGE || -v HELP ]]; then
-	exit 0
+    exit 0
 fi
 
 envs=(
-	reg-us-east-1
-	dev-us-east-1
+    reg-us-east-1
+    dev-us-east-1
 )
 
 for env in "${envs[@]}"; do
-	url=$(eureka -e $env event-service-consumer-proxy | sed 's:/$::') || {
-		echo "[!] event-service-consumer-proxy not found..."
-		continue
-	}
+    url=$(eureka -e "$env" event-service-consumer-proxy | sed 's:/$::') || {
+        echo "[!] event-service-consumer-proxy not found..."
+        continue
+    }
 
-	if [[ -v DUMP ]]; then
-		mxcurl $url/subscriptions | jq .
-		ANYTHING=1
-	else
+    if [[ -v DUMP ]]; then
+        mxcurl "$url/subscriptions" | jq .
+        ANYTHING=1
+    else
 
-		if [[ -v PATTERN ]]; then
-			query="._embedded.subscriptions[]? | select(.name | test(\"$PATTERN\"))"
-		else
-			if [[ ! -v IDENTITY ]]; then
-				IDENTITY="$(
-					. ~/.ssh/P2020
-					echo "$P2020_IDENTITY_CLIENT_ID"
-				)"
-			fi
-			query="._embedded.subscriptions[]? | select(.clientID == \"$IDENTITY\")"
-		fi
+        if [[ -v PATTERN ]]; then
+            query="._embedded.subscriptions[]? | select(.name | test(\"$PATTERN\"))"
+        else
+            if [[ ! -v IDENTITY ]]; then
+                IDENTITY="$(
+                    . ~/.ssh/P2020
+                    echo "$P2020_IDENTITY_CLIENT_ID"
+                )"
+            fi
+            query="._embedded.subscriptions[]? | select(.clientID == \"$IDENTITY\")"
+        fi
 
-		payloads=("$(mxcurl $url/subscriptions | jq -r --arg HOST "$HOSTNAME" "$query")")
+        payloads=("$(mxcurl "$url/subscriptions" | jq -r --arg HOST "$HOSTNAME" "$query")")
 
-		for body in "${payloads[@]}"; do
-			[[ "$body" ]] || continue
-			ANYTHING=1
-			if [[ -v VERBOSE ]]; then
-				jq . <<<"$body"
-			elif [[ -v NAMES ]]; then
-				jq -r '.name' <<<"$body"
-			elif [[ -v LINKS ]]; then
-				jq -r '.deliveryMethod.endpoint' <<<"$body"
-			else
-				jq -r '.id.href' <<<"$body"
-			fi
-			if [[ -v DELETE ]]; then
-				mxcurl -X DELETE $(jq -r '.id.href' <<<"$body") | sed 's/^$/deleted/'
-			fi
-		done
-	fi
+        for body in "${payloads[@]}"; do
+            [[ "$body" ]] || continue
+            ANYTHING=1
+            if [[ -v VERBOSE ]]; then
+                jq . <<< "$body"
+            elif [[ -v NAMES ]]; then
+                jq -r '.name' <<< "$body"
+            elif [[ -v LINKS ]]; then
+                jq -r '.deliveryMethod.endpoint' <<< "$body"
+            else
+                jq -r '.id.href' <<< "$body"
+            fi
+            if [[ -v DELETE ]]; then
+                jq -r '.id.href' <<< "$body" | xargs -r mxcurl -X DELETE --write-out "%{method}: %{response_code}"
+            fi
+        done
+    fi
 done
 
 if [[ ! -v ANYTHING && ! -v QUIET ]]; then
-	echo "[.] Nothing matched"
+    echo "[.] Nothing matched"
 fi
