start AWS workspace move

diff --git a/bin/taskify b/bin/taskify
--- a/bin/taskify
+++ b/bin/taskify
@@ -13,19 +13,28 @@
 # - logrotate?
 
 
+die() {
+    echo "taskify: $@"
+    [[ $LOG ]] && echo "taskify: $@" >> $LOG
+    exit 1
+}
+
 while [[ $# -gt 0 ]]; do
     arg="$1" ; shift
     case $arg in
         --) break ;;
         -h|--help)
             HELP=1 ;;
-        -s|--sleep)
+        -s|--random-sleep)
             TIMEOUT="$1"
             shift ;;
         -q|--quiet)
             QUIET=1 ;;
         -l|--log)
             LOG="$1"
+            shift ;;
+        -d|--directory)
+            DIRECTORY="$1"
             shift ;;
         -*)
             echo "[X] I don't understand this argument: ($arg)"
@@ -46,7 +55,7 @@ fi
 
 if [[ $HELP ]]; then
     cat <<EOF
-Usage: $0 [-h|--help] [-s|--sleep TIMEOUT] [-q|--quiet] [--] COMMAND ...
+Usage: $(basename $0) [OPTIONS] [--] COMMAND ...
 
 Sanitize commands for cron.
 
@@ -54,12 +63,17 @@ Arguments:
 COMMAND                 The command to run, with arguments
 
 Options:
--h|--help               Print out this message.
--s|--sleep TIMEOUT      Sleep for a random duration up to TIMEOUT seconds before executing the command (to prevent load
-                        spikes at midnight, etc).
--q|--quiet              Silence the command, unless it exits with an error (to prevent useless cron emails from chatty
-                        programs).
--l|--log LOG            Append any output to LOG as well (includes timestamp & exit code)
+-h|--help       Print out this message.
+-q|--quiet      Silence the command, unless it exits with an error (to prevent
+                useless cron emails from chatty programs).
+-l|--log LOG    Append any output to LOG as well (includes timestamp & exit
+                code; path LOG is *not* relative to --directory argument)
+-s|--random-sleep TIMEOUT
+                Sleep for a random duration up to TIMEOUT seconds before
+                executing the command (to prevent load spikes at midnight,
+                etc).
+-d|--directory DIRECTORY
+                change to DIRECTORY before executing command
 EOF
 
     exit 1
@@ -69,8 +83,16 @@ if [[ $TIMEOUT ]]; then
     sleep $(( RANDOM % TIMEOUT ))
 fi
 
+if [[ $DIRECTORY ]]; then
+    pushd $DIRECTORY &> /dev/null || die "could not change directory to ($DIRECTORY)"
+fi
+
 output="$( eval "${COMMAND[@]}" 2>&1 )"
 status=$?
+
+if [[ $DIRECTORY ]]; then
+    popd &> /dev/null
+fi
 
 if [[ ! $QUIET || $status -ne 0 ]]; then
     [[ $output ]] && echo "$output"
diff --git a/maxar-bin/list-subscriptions b/maxar-bin/list-subscriptions
--- a/maxar-bin/list-subscriptions
+++ b/maxar-bin/list-subscriptions
@@ -1,16 +1,18 @@
 #!/usr/bin/env bash
 # vim: tw=0
 
-trap 'echo "got ($?) on line ($LINENO): $BASH_COMMAND"' ERR
-
 set -eEuo pipefail
+trap 'echo "err ($?) at ($BASH_SOURCE:$LINENO): $BASH_COMMAND"' ERR
 
 while [[ $# -gt 0 ]]; do
     arg="$1"; shift
     case $arg in
+        (-*=*)
+            # split --var=value pairs into separate tokens
+            # but only replacing the first '='!
+            set -- $(echo $arg | sed 's/=/ /' ) "$@" ;;
         (-d|--dump)
-            DUMP=1
-            ;;
+            DUMP=1 ;;
         (-v|--verbose)
             VERBOSE=1
             unset DUMP NAMES LINKS
@@ -57,15 +59,16 @@ if [[ -v HELP ]]; then
 
 Options:
 
--h|--help           Print this text and exit.
--q|--quiet          Suppress the informational output displayed when no services are matched
--d|--dump           Don't attempt to match against anything; dump all subscription json
--v|--verbose        Dump the full subscription json
--n|--names          Output names instead of links
--m|--match-name     Match the subscription name against this (jq) regex
--i|--identity       match based on this P2020 client identity
+-h|--help       Print this text and exit.
+-q|--quiet      Suppress the informational output displayed when no services are matched
+-d|--dump       Don't attempt to match against anything; dump all subscription json
+-v|--verbose    Dump the full subscription json
+-n|--names      Output names instead of links
 
---delete            after printing, delete matched subscriptions (be careful!)
+-m|--match-name=NAME    Match the subscription name against this (jq) regex
+-i|--identity=PATH      Match based on this P2020 client identity
+
+--delete        after displaying, delete matched subscriptions (be careful!)
 
 In the case of conflicting options, the last option specified on the command
 line takes precedence.
@@ -86,7 +89,7 @@ envs=(
 )
 
 for env in "${envs[@]}"; do
-    url=$(eureka -e $env event-service-consumer-proxy | sed 's:/$::')
+    url=$(eureka -e $env event-service-consumer-proxy | sed 's:/$::') || { echo "[!] event-service-consumer-proxy not found..." ; continue ; }
 
     if [[ -v DUMP ]]; then
         mxcurl $url/subscriptions | jq .
@@ -117,7 +120,7 @@ for env in "${envs[@]}"; do
                 jq -r '.id.href' <<< "$body"
             fi
             if [[ -v DELETE ]]; then
-                mxcurl -X DELETE $( jq -r '.id.href' <<< "$body" )
+                mxcurl -X DELETE $( jq -r '.id.href' <<< "$body" ) | sed 's/^$/deleted/'
             fi
         done
     fi
