applied `shfmt` everywhere

diff --git a/dotfiles/bin/pack b/dotfiles/bin/pack
--- a/dotfiles/bin/pack
+++ b/dotfiles/bin/pack
@@ -21,12 +21,17 @@ if [[ $@ ]]; then
 fi
 
 for i in {1..3}; do
-    read -sp "[>] choose a password: " PASSWORD ; echo
-    read -sp "[>] confirm password: " CONFIRM ; echo
-    [[ $PASSWORD = $CONFIRM ]] && break
+    read -sp "[>] choose a password: " PASSWORD
+    echo
+    read -sp "[>] confirm password: " CONFIRM
+    echo
+    [[ $PASSWORD == $CONFIRM ]] && break
     echo "[!] passwords did not match"
 done
-[[ $PASSWORD = $CONFIRM ]] || { echo "[X] go get some coffee..." ; exit 1 ;}
+[[ $PASSWORD == $CONFIRM ]] || {
+    echo "[X] go get some coffee..."
+    exit 1
+}
 
 echo "[.] starting: $(date)"
 
@@ -37,15 +42,15 @@ tar -czf $INPUT/backup-bin.tgz -C $NFS_ROOT bin
 # make a local copy of all yum installs
 rm $INPUT/installs.txt || true
 yumdb search command_line '*' > $INPUT/installs.txt
-( yum history info '*' || echo "[X] could not read history" ) &> $INPUT/yum-history.txt
+(yum history info '*' || echo "[X] could not read history") &> $INPUT/yum-history.txt
 
 # grab crontab
 crontab -l > $INPUT/$USER.crontab || true
 
 # backup our input directory, with compression & encryption
-tar --exclude-caches --warning=none -P -c "$INPUT" \
-    | zstd \
-    | PASSWORD="$PASSWORD" openssl aes-256-cbc -e -pbkdf2 -pass env:PASSWORD -out "$OUTPUT"
+tar --exclude-caches --warning=none -P -c "$INPUT" |
+    zstd |
+    PASSWORD="$PASSWORD" openssl aes-256-cbc -e -pbkdf2 -pass env:PASSWORD -out "$OUTPUT"
 
 ls -lhF "$OUTPUT"
 echo "[.] complete: $(date)"
@@ -57,17 +62,17 @@ trap 'echo "err ($?) on line ($LINENO): $BASH_COMMAND"' ERR
 
 : ${NFS_ROOT:=/nfshome/testdev/$USER}
 
-INPUT=$(find $NFS_ROOT/backups -type f -name '*.tar.zst.aes'| sort | tail -n 1)
+INPUT=$(find $NFS_ROOT/backups -type f -name '*.tar.zst.aes' | sort | tail -n 1)
 
 read -sp "password: " PASSWORD
 echo
 
 echo "starting: $(date)"
 
-PASSWORD="$PASSWORD" $NFS_ROOT/bin/openssl aes-256-cbc -d -pbkdf2 -pass env:PASSWORD -in "$INPUT" \
-    | $NFS_ROOT/bin/zstd -d \
-    | tar -C / -x --overwrite
-    # > $HOME/restore.tar
-    # | tar -C / -t
+PASSWORD="$PASSWORD" $NFS_ROOT/bin/openssl aes-256-cbc -d -pbkdf2 -pass env:PASSWORD -in "$INPUT" |
+    $NFS_ROOT/bin/zstd -d |
+    tar -C / -x --overwrite
+# > $HOME/restore.tar
+# | tar -C / -t
 
 echo "complete: $(date)"
