2024-09-14 checkpoint

diff --git a/dotfiles/bin/taskify b/dotfiles/bin/taskify
--- a/dotfiles/bin/taskify
+++ b/dotfiles/bin/taskify
@@ -2,57 +2,48 @@
 
 # All the little snippets I've thrown into cron jobs, collected and modularized.
 
-MY_NAME="$(basename "$0")"
+# use all my bashy goodness
+source ~/.bashrc
+
+MY_NAME=$(basename "$0")
 
 die() {
-    echo "$MY_NAME: $*"
-    [[ $LOG ]] && echo "$MY_NAME: $*" >> "$LOG"
+    echo "$MY_NAME: ${*:-Fatal Error}" | tee -a "${LOG:-/dev/null}"
     exit 1
 }
 
-while [[ $# -gt 0 ]]; do
-    arg="$1"
-    shift
-    case $arg in
-        --) break ;;
-        -h | --help)
-            HELP=1
-            ;;
-        -s | --random-sleep)
-            TIMEOUT="$1"
-            shift
-            ;;
-        -q | --quiet)
-            QUIET=$((${QUIET:-0} + 1))
-            ;;
-        -l | --log)
-            LOG="$1"
-            shift
-            ;;
-        -d | --directory)
-            DIRECTORY="$1"
-            shift
-            ;;
-        -*)
-            echo "[X] I don't understand this argument: ($arg)"
-            HELP=1
-            ;;
-        *)
-            # put this arg back on the stack
-            set -- "$arg" "$@"
-            break
-            ;;
+ARGS=$(
+    getopt \
+        -o 'hs:qvl:d:L:S:' \
+        --long 'help,random-sleep:,quiet,verbose,log:,directory:,longer-than:,shorter-than:' \
+        -n "$MY_NAME" \
+        -- "$@"
+) || die "Halting for invalid arguments"
+eval set -- "$ARGS" && unset ARGS
+
+declare HELP
+declare TIMEOUT LOGFILE DIRECTORY LONGER SHORTER
+declare COMMAND
+
+declare VOLUME=3
+
+while (($#)); do
+    case $1 in
+        -h | --help) HELP=1 && shift ;;
+        -s | --random-sleep) TIMEOUT=$2 && shift 2 ;;
+        -q | --quiet) ((VOLUME--)) && shift ;;
+        -l | --log) LOGFILE=$2 && shift 2 ;;
+        -d | --directory) DIRECTORY=$2 && shift 2 ;;
+        -L | --longer-than) LONGER=$2 && shift 2 ;;
+        -S | --shorter-than) SHORTER=$2 && shift 2 ;;
+        --) shift && break ;;
+        *) break ;;
     esac
 done
 
 COMMAND=("$@")
 
-if [[ ! $HELP && ! ${COMMAND[*]} ]]; then
-    echo "[X] No command supplied"
-    HELP=1
-fi
-
-if [[ $HELP ]]; then
+if [[ ${HELP-} ]]; then
     cat << EOF
 Usage: $MY_NAME [OPTIONS] [--] COMMAND ...
 
@@ -72,39 +63,65 @@ Options:
                 Sleep for a random duration up to TIMEOUT seconds before
                 executing the command (to prevent load spikes at midnight,
                 etc).
+-S|--shorter-than DURATION
+                If the command executes for fewer seconds than DURATION, 
 -d|--directory DIRECTORY
                 change to DIRECTORY before executing command
 EOF
 
-    exit 1
+    exit
 fi
 
-if [[ $TIMEOUT ]]; then
+if [[ ${TIMEOUT-} ]]; then
     sleep $((RANDOM % TIMEOUT))
 fi
 
-if [[ $DIRECTORY ]]; then
+if [[ ${DIRECTORY-} ]]; then
     pushd "$DIRECTORY" &> /dev/null || die "could not change directory to ($DIRECTORY)"
 fi
 
+starttime=$EPOCHSECONDS
 output=$("${COMMAND[@]}" 2>&1)
-status=$?
+exit_code=$?
+stoptime=$EPOCHSECONDS
 
-if [[ $DIRECTORY ]]; then
+if [[ ! ${output-} ]]; then
+    empty=1
+    output="[.] no output"
+fi
+
+output+=$'\n'
+output+="[.] exit code: $exit_code"
+
+duration=$((stoptime - starttime))
+
+if [[ ${LONGER-} && $duration -gt $LONGER ]]; then
+    TOOK_LONGER=1
+fi
+
+if [[ ${SHORTER-} && $duration -le $SHORTER ]]; then
+    TOOK_SHORTER=1
+fi
+
+if [[ ${TOOK_LONGER-} || ${TOOK_SHORTER-} ]]; then
+    output+=$'\n'
+    output+="[.] duration: $duration"
+    VOLUME=3
+fi
+
+if [[ ${DIRECTORY-} ]]; then
     popd &> /dev/null || die "could not return to starting directory"
 fi
 
-if [[ ! $QUIET || ($QUIET -lt 2 && $status -ne 0) ]]; then
-    [[ $output ]] && echo "$output"
+if [[ ($VOLUME -gt 2 && ! ${empty-}) || ($VOLUME -gt 1 && $exit_code -ne 0) ]]; then
+    echo "$output"
 fi
 
-if [[ $LOG ]]; then
-    [[ $output ]] || output='(no output)'
+if [[ ${LOGFILE-} ]]; then
     {
-        date
+        echo "[.] date: $(date +%c)"
         echo "$output"
-        echo "exit code $status"
-    } >> "$LOG"
+    } >> "$LOGFILE"
 fi
 
-exit $status
+exit $exit_code
